### ISSUE TITLE
Prevent inclusion in autofill text

### ISSUE THREAD

**Issue by amandamana** [a161803398/ShowPassword#1]
I'm experiencing a security problem where Chrome saves my passwords as autofill text. The next time I revisit a form to type my password, the field shows a dropdown containing my password from a previous submission. This only happens if my passwords is showing in clear text at the time that I submit the form. If I let the password return to bullets (e.g, by losing focus or un-hovering) then Chrome does not save the autofill text. Can ShowPassword do something to ensure that passwords are never saved for autofill?

**Comment by a161803398** [comment]
Thank you for your report.
I think I can fix the problem by change password field back into "password" when user press enter or password field lost focus (that means user press submit button, so it lost focus).

I have already fixed it on version 1.1.5, please test it, thank you !

**Comment by amandamana** [comment]
Confirmed fixed. Great job!
